version: '3'
services:
  tracker_rs41_4027:
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - PORT=5001
      - CONFIG_FILE=config.4027.json
      - WEBSOCKET_PORT=7001
    ports:
      - 5001:5000/tcp
      - 4027:4030/udp
      - 7001:7001/tcp

  tracker_rs41_4030:
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - PORT=5002
      - CONFIG_FILE=config.4030.json
      - WEBSOCKET_PORT=7002
    ports:
      - 5002:5000/tcp
      - 4030:4030/udp
      - 7002:7002/tcp

  tracker_rs41_4033:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - PORT=5003
      - CONFIG_FILE=config.4033.json
      - WEBSOCKET_PORT=7003
    network_mode: host
    ports:
      - 5003:5000
      - 4033:4030
      - 7003:7003
