version: '3'
services:
  tracker_rs41_4027:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=config.json
      - WEBSOCKET_PORT=7001
    ports:
      - 5001:5000/tcp
      - 4027:4030/udp
      - 7001:7001

  tracker_rs41_4030:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=config.json
      - WEBSOCKET_PORT=7002
    ports:
      - 5002:5000/tcp
      - 4030:4030/udp
      - 7002:7002

  tracker_rs41_4033:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE=config.json
      - WEBSOCKET_PORT=7003
    ports:
      - 5003:5000/tcp
      - 4033:4030/udp
      - 7003:7003
